### ISSUE TITLE
gdrive files not opening from within google drive

### ISSUE THREAD

**Issue by adamjimenez** [adamjimenez/shiftedit#109]

**Comment by geoffreykolbe** [comment]
I am having an issue that Google Drive is not opening. The wheel just keeps going around. The only way I can open it is to to to 'update details' and click on 'launch' from there. The ShiftEdit page loads up again and Google Drive files appear almost immediately.

**Comment by geoffreykolbe** [comment]
The problem turned out to be that I have an app which stops pop-up windows, which usually have unwanted adverts. But in this case, it stops the pop-up asking me for permission to go into Google Drive. I gave the app specific permission for pop-ups on the Shiftedit site and now everything works fine.
